name: Ignition
author: Ninja3047
main: com.github.Ninja3047.Ignition.Ignition
version: 0.2

commands:
  ignite:
    description: Ignites a player on fire
    aliases: [ig]
    usage: /<command> [player]
    permission: Ignition.ignite
    permission-message: You don't have <permission>
  strike:
    description: Strikes a player with lightning
    aliases: [str]
    usage: /<command> [player]
    permission: Ignition.strike
    permission-message: You don't have <permission>